### PR TITLE
Add pre-publication banner to fade

### PR DESCRIPTION
**Pull request by rdvelazquez**
screen shot 2019-02-15 at 10 16 36 am

### CODE REVIEW

**Comment by stevenweaver** [comment]
screen shot 2019-02-15 at 10 25 33

Can we place a *Beta* badge on the dropdown menu? I think it will be ready to go after that.

**Comment by stevenweaver** [comment]
https://getbootstrap.com/docs/4.0/components/badge/

**Comment by rdvelazquez** [comment]
How's this look?
screen shot 2019-02-15 at 10 36 55 am

**Comment by rdvelazquez** [comment]
Or we could use the green (which I like a bit better):
screen shot 2019-02-15 at 10 40 02 am

**Pull request merged**
